=== kilesz/I5XJTC_XMLGyak/I5XJTC_1004/I5XJTC_kurzusfelvetel.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE I5XJTC_kurzusfelvetel [
	<!ELEMENT I5XJTC_kurzusfelvetel (kurzusfelvetel)>
		<!ATTLIST I5XJTC_kurzusfelvetel id ID #REQUIRED>
		<!ATTLIST I5XJTC_kurzusfelvetel nev ID #REQUIRED>
		<!ELEMENT kurzusfelvetel (kurzus*)>
			<!ELEMENT kurzus (kurzusnev, kredit, hely, idopont+, oktato?)>
				<!ATTLIST kurzus id ID #REQUIRED>
				<!ATTLIST kurzus jovahagyas (igen|nem) #REQUIRED "nem">
				<!ELEMENT kurzusnev (#PCDATA)>
				<!ELEMENT kredit (#PCDATA)>
				<!ELEMENT idopont (#PCDATA)>
				<!ELEMENT oktato (#PCDATA)>
]>

=== kilesz/I5XJTC_XMLGyak/I5XJTC_1004/I5XJTC_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE I5XJTC_kurzusfelvetel SYSTEM "I5XJTC_kurzusfelvetel.dtd">

<I5XJTC_kurzusfelvetel tanev="2023/2024">
	<kurzusfelvetel>
		<kurzus id="GEIAL332-B" jovahagyas="igen">
			<kurzusnev>Adatkezelés XML környezetben</kurzusnev>
			<kredit>5</kredit>
			<hely>XXXII.</hely>
			<idopont>Kedd 12:00-13:30</idopont>
			<oktato>Dr. Bednarik László</oktato>
		</kurzus>
	</kurzusfelvetel>
</I5XJTC_kurzusfelvetel>
