=== kilesz/I5XJTC_XMLGyak/I5XJTC_1122/xPathI5XJTC/studentI5XJTC.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="class">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" minOccurs="3" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="keresztnev" type="xs:string" minOccurs="1" maxOccurs="1" />
                            <xs:element name="vezeteknev" type="xs:string" minOccurs="1" maxOccurs="1" />
                            <xs:element name="becenev" type="xs:string" />
                            <xs:element name="kor" type="xs:integer" minOccurs="1" maxOccurs="1" />
							<xs:element name="osztondij" type="xs:integer" minOccurs="1" maxOccurs="1" />
                        </xs:sequence>
                            <xs:attribute name="id" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== kilesz/I5XJTC_XMLGyak/I5XJTC_1122/xPathI5XJTC/studentI5XJTC_1.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<class xmlns:xs="http://www.w3.org/2001/XMLSchema" xs:noNamespaceSchemaLocation="studentI5XJTC.xsd">
        
    <student id="01">
                
        <vezeteknev>Katona</vezeteknev>
                
        <keresztnev>Bence</keresztnev>
         
        
        <becenev>Bence</becenev>
                
        <kor>22</kor>
                
        <osztondij>30000</osztondij>
          
    
    </student>
      
    
    <student id="02">
          
        
        <vezeteknev>Nagy</vezeteknev>
                
        <keresztnev>Bence</keresztnev>
                
        <becenev>Bence</becenev>
                
        <kor>23</kor>
                
        <osztondij>25000</osztondij>
            
    </student>
        
    <student id="03">
                
        <vezeteknev>Meszaros</vezeteknev>
                
        <keresztnev>Szabolcs</keresztnev>
                
        <becenev>Szabi</becenev>
                
        <kor>21</kor>
                
        <osztondij>35000</osztondij>
            
    </student>
    
    <szak>GEIK</szak>
</class>
